In [1]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the datasets
data=pd.read_csv('Data.csv')

In [13]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [16]:
data.shape

(10, 4)

In [17]:
# Creating the matrix of features. In the imported dataset Country, Age, Salary are independent variables
X = data.iloc[:, :-1].values

In [18]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
# Creating the dependent variable
y = data.iloc[:, 3].values

In [20]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [21]:
# Taking care of missing data
from sklearn.preprocessing import Imputer

In [22]:
# Creating the object of Imputer class
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)


In [23]:
# fit imputer object to data X (Matrix of feature X)
imputer = imputer.fit(X[:, 1:3]) 

In [24]:
imputer

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [25]:
# Replace the missing data of column by mean
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [26]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [27]:
# Encoding categorical data
# Creating dummy variables using OneHotEncoder class
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 

In [28]:
# Creating the object of LabelEncoder class
labelencoder_X = LabelEncoder()


In [29]:
# fit labelencoder_X object to first coulmn Country of matrix X
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [30]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [31]:
# Creating dummy variables
# Creating the object of OneHotEncoder class
onehotencoder = OneHotEncoder(categorical_features = [0])

In [32]:
# fit onehotencoder object to first column - Country of matrix X
X = onehotencoder.fit_transform(X).toarray()

In [33]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [34]:
# Creating the object of LabelEncoder class
labelencoder_y = LabelEncoder()

In [35]:
# fit labelencoder_y object to last coulmn Purchased, we will get encoded vector
y = labelencoder_y.fit_transform(y)

In [36]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [37]:

# Splitting the dataset into training set and test set
from sklearn.cross_validation import train_test_split

C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [38]:
# Choosing 20% data as test data, so we will have 80% data in training set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [43]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8, 5)
(2, 5)
(8,)
(2,)


In [39]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

In [40]:
# Creating the object of StandardScaler
sc_X = StandardScaler()

In [41]:
# fit and transform training set
X_train = sc_X.fit_transform(X_train)

In [42]:
# transform test set
X_test = sc_X.transform(X_test)