In [1]:
#https://www.codespeedy.com/vector-addition-and-subtraction-in-python/

import numpy as NP
A = [4, 8, 7]
B = [5, -4, 8]
print("The input arrays are :\n","A:",A ,"\n","B:",B)
Res= NP.add(A,B)
print("After addition the resulting array is :",Res)

The input arrays are :
 A: [4, 8, 7] 
 B: [5, -4, 8]
After addition the resulting array is : [ 9  4 15]


In [2]:
import numpy as NP
A = [4, 8, 7] 
B = [5, -4, 8] 
print("The input arrays are :\n","A:",A ,"\n","B:",B)
Res1= NP.add(A,B)
Res2= NP.subtract(A,B) 
print("Result of Addition is :",Res1,"\n","Result of Subtraction is:",Res2)

The input arrays are :
 A: [4, 8, 7] 
 B: [5, -4, 8]
Result of Addition is : [ 9  4 15] 
 Result of Subtraction is: [-1 12 -1]


In [3]:
# create a vector
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


In [4]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [5]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([0.5, 0.5, 0.5])
print(b)
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [6]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [7]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


In [8]:

# dot product vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [9]:

# VECTOR AND SCALAR
from numpy import array
a = array([1, 2, 3])
print(a)
s = 0.5
print(s)
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
